// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhbnrywzljjtawoufmmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoYm5yeXd6bGpqdGF3b3VmbW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NTI4MTgsImV4cCI6MjA4NzUyODgxOH0.CgZOkOk3gCaIvotgxIHsidZwsZq-WlyMpw248puWkXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});